on:
  push:
    branches:
      - main
      - develop

name: "🐦 Build Flutter to Firebase Distribution"

jobs:
  flutter_test:
    name: 💪🏻 Run flutter test and analyze
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/uat' ||
      github.ref == 'refs/heads/develop' ||
      startsWith(github.event.head_commit.message, '[BUILD')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: 🛠 Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.8.1"
          channel: "stable"
      - name: ⌛️ Run flutter pub get...
        run: flutter pub get
      - name: 🔎 Run flutter analyze... (Treat Warning only)
        run: flutter analyze --no-fatal-infos
      - name: ⌛️ Run flutter test...
        run: flutter test
  
  build_android:
    name: 🤖 Build Android application...
    needs: [flutter_test]
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/develop' ||
      startsWith(github.event.head_commit.message, '[BUILD')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: 🔑 Decode Keystore (debug)
        if: |
          github.ref == 'refs/heads/develop' ||
          startsWith(github.event.head_commit.message, '[BUILD')
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/debug.keystore'
          encodedString: ${{ secrets.ENCODED_KEYSTORE_DEBUG }}

      - name: 🤐 Add env
        env: 
          ENV_DEV : ${{ secrets.ENV_DEV }}
        run: echo $ENV_DEV > .env.dev

      - name: 🔥 Decode Firebase Service
        env:
          FIREBASE_CONFIG: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $FIREBASE_CONFIG > android/app/google-services.json

      - name: 🛠 Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.x"
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean

      - name: 🚀 Build application (dev:debug)...
        if: |
          github.ref == 'refs/heads/develop' ||
          startsWith(github.event.head_commit.message, '[BUILD')
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS_DEBUG }}
          SIGNING_PASSWORD: ${{ secrets.KEY_PASS_DEBUG }}
        #- run: flutter build appbundle
        run: flutter build apk --flavor dev --debug

name: "✨ Firebase Distribute"
jobs:
  if: |
    github.ref == 'refs/heades/develop' ||
    startWith(github.event.head_commit.message, '[BUILD PROD]')
  steps:
    - name: ☁️ Upload .apk to Firebase App Distribution prod
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_DISTRIBUTE_APP_ID_DEV}}
        token: ${{secrets.FIREBASE_CLI_TOKEN}}
        file: build/app/outputs/apk/dev/debug/app-dev-debug.apk

  if : |
    github.ref == 'refs/heades/develop' ||
    startWith(github.event.head_commit.message, '[BUILD DEV]')
  steps:
    - name: ☁️ Upload .apk to Firebase App Distribution dev
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_DISTRIBUTE_APP_ID_PROD}}
        token: ${{secrets.FIREBASE_CLI_TOKEN}}
        file: build/app/outputs/apk/dev/debug/app-dev-debug.apk
   